/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seng3120_geometry_calculator_gradle_java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
