/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seng3120_geometry_calculator_gradle_java;

import org.junit.Test;
import static org.junit.Assert.*;
import Cylinder;

public class CylinderTest {
    @Test public void cylVolume() {
        Cylinder classUnderTest = new Cylinder();
        assertEquals(Math.PI * 1 * 1 * 2, classUnderTest.volume(1, 2), 0.0);
    }
}
